version: '3.4'

services:

  eventstore:
    image: eventstore
    build:
      context: .
      dockerfile: Apps/EventStore.App/Dockerfile
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - ES_CONNECTION=Server=database_sql;Database=event_sourcing;User Id=sa;Password=Pass@word
    depends_on:
    - database_sql

  trackers:
    image: trackers
    build:
      context: .
      dockerfile: MicroServices/Trackers/Trackers.Service/Dockerfile
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - ES_CONNECTION=Server=database_sql;Database=event_sourcing;User Id=sa;Password=Pass@word
    - DB_CONNECTION=Server=database_sql;Database=trackers;User Id=sa;Password=Pass@word
    - DISTRIBUTED_CACHE=distributed_cache
    - RABBIT_CONNECTION=amqp://test:test@rabbitmq:5672
    depends_on:
    - database_sql  
    - eventstore
    - rabbitmq

    
  vehicles:
    image: vehicles
    build:
      context: .
      dockerfile: MicroServices/Vehicles/Vehicles.Service/Dockerfile
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - ES_CONNECTION=Server=database_sql;Database=event_sourcing;User Id=sa;Password=Pass@word
    - DB_CONNECTION=Server=database_sql;Database=vehicles;User Id=sa;Password=Pass@word
    - DISTRIBUTED_CACHE=distributed_cache
    - RABBIT_CONNECTION=amqp://test:test@rabbitmq:5672
    depends_on:
    - database_sql  
    - eventstore
    - rabbitmq

  servicegateway:
    image: servicegateway
    build:
      context: .
      dockerfile: Gateway/ServicesGateway/Dockerfile
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
    - trackers
    - vehicles
    - rabbitmq
    ports:
    - 6543:80

  #### RabbitMQ Container ####
  rabbitmq:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "test"
      RABBITMQ_DEFAULT_PASS: "test"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
    - 15672:15672
    - 5672:5672

  database_sql:
    image: mcr.microsoft.com/mssql/server
    environment:
    - MSSQL_SA_PASSWORD=Pass@word
    - ACCEPT_EULA=Y
    - MSSQL_PID=Express
    ports:
    - 5553:1433
